import { z } from 'zod';
import { CampaignPlan, CampaignInput } from '@platform/campaign-engine';
import { llmService } from '../llm.service';

// --- Zod Schema for AI Output ---
const EnhancementResponseSchema = z.object({
    adGroupEnhancements: z.array(z.object({
        adGroupName: z.string(),
        newHeadlines: z.array(z.string().max(30)).optional(),
        newDescriptions: z.array(z.string().max(90)).optional()
    })).optional(),
    keywordExpansions: z.array(z.object({
        clusterTheme: z.string(),
        newKeywords: z.array(z.object({
            term: z.string(),
            matchType: z.enum(['Exact', 'Phrase', 'Broad'])
        }))
    })).optional(),
    landingPageInsights: z.array(z.string()).optional()
});

type EnhancementResponse = z.infer<typeof EnhancementResponseSchema>;

/**
 * AI Enhancement Layer
 * 
 * Takes a deterministically generated "Skeleton Plan" and applies LLM intelligence 
 * to refine copy, expand keywords, and polish strategy using a "Patch" approach.
 */
export class BlueprintAiEnhancer {

    /**
     * Enhances a campaign plan using Generative AI.
     */
    async enhance(plan: CampaignPlan, input: CampaignInput): Promise<CampaignPlan> {
        console.log('--- AI ENHANCEMENT LAYER STARTED ---');

        // 1. Construct the Enhancement Prompt
        const prompt = this.buildEnhancementPrompt(plan, input);

        // 2. Call LLM (Gemini/OpenAI)
        try {
            const enhancedJson = await llmService.generateJSON(prompt, { temperature: 0.7 });

            // 3. Robust Cleaning Layer (Truncate if AI ignores limits)
            const cleanJson = this.enforceLimits(enhancedJson);

            // 4. Validation Layer
            const validatedPatch = EnhancementResponseSchema.parse(cleanJson);

            // 4. Merge Patch into Original Plan
            return this.applyEnhancements(plan, validatedPatch);

        } catch (error) {
            console.error('AI Enhancement Failed, falling back to Rule Engine plan:', error);
            // Fallback: Return original plan if AI fails
            return plan;
        }
    }

    private buildEnhancementPrompt(plan: CampaignPlan, input: CampaignInput): string {
        const verticalGuidance = this.getVerticalGuidance(input.vertical);

        return `
You are a World-Class Google Ads Strategist specializing in the **${input.vertical}** industry.
I have a "Draft Campaign Plan" generated by a Rule Engine. 
Your job is to ENHANCE it by returning a "Patch Object" with specific improvements.

BUSINESS CONTEXT:
Name: ${input.businessName}
Vertical: ${input.vertical}
Offer: ${input.offer}
Location: ${input.geo}
Pain Points: ${input.painPoints?.join(', ') || 'N/A'}

STRATEGIC GOAL:
${verticalGuidance}

INSTRUCTIONS:
1. **Refine Ad Copy (RSAs):** 
   - Review the Ad Groups in the Input Plan.
   - For key Ad Groups, provide 3-5 *new, high-impact* headlines (max 30 chars).
   - Provide 1-2 *benefit-driven* descriptions (max 90 chars).
   - Focus on "What's in it for the customer?".
   - Avoid generic phrases like "Best Service". Be specific.

2. **Expand Keywords:** 
   - For each Keyword Cluster, identify 2-3 "semantic" or "long-tail" keywords that a regex might miss.
   - Ensure they match the cluster's Intent.

3. **Strategic Recommendations:**
   - Add 2 specific, actionable recommendations for the Landing Page strategy based on the ${input.vertical} industry.

INPUT PLAN (JSON):
${JSON.stringify({
            adGroups: plan.adGroups?.map(ag => ({ name: ag.adGroupName, assets: ag.rsaAssets })),
            keywordClusters: plan.keywordClusters
        }, null, 2)}

OUTPUT SCHEMA (JSON):
{
  "adGroupEnhancements": [
    { 
      "adGroupName": "string (must match input)", 
      "newHeadlines": ["string (max 30 chars)"], 
      "newDescriptions": ["string (max 90 chars)"] 
    }
  ],
  "keywordExpansions": [
    { 
      "clusterTheme": "string (must match input)", 
      "newKeywords": [ { "term": "string", "matchType": "Broad" | "Phrase" | "Exact" } ] 
    }
  ],
  "landingPageInsights": ["string (recommendation)"]
}

Return VALID JSON only. Do not return the full plan, only the enhancements.
`;
    }

    private applyEnhancements(original: CampaignPlan, patch: EnhancementResponse): CampaignPlan {
        console.log('Applying AI Enhancements...');

        // 1. Merge Ad Copy
        if (patch.adGroupEnhancements && original.adGroups) {
            patch.adGroupEnhancements.forEach(enhancement => {
                const targetGroup = original.adGroups?.find(g => g.adGroupName === enhancement.adGroupName);
                if (targetGroup && targetGroup.rsaAssets) {
                    if (enhancement.newHeadlines) {
                        // Prepend new AI headlines to prioritize them
                        targetGroup.rsaAssets.headlines = [
                            ...enhancement.newHeadlines,
                            ...targetGroup.rsaAssets.headlines
                        ].slice(0, 15); // Max 15
                    }
                    if (enhancement.newDescriptions) {
                        targetGroup.rsaAssets.descriptions = [
                            ...enhancement.newDescriptions,
                            ...targetGroup.rsaAssets.descriptions
                        ].slice(0, 4); // Max 4
                    }
                }
            });
        }

        // 2. Merge Keywords
        if (patch.keywordExpansions && original.keywordClusters) {
            patch.keywordExpansions.forEach(expansion => {
                const targetCluster = original.keywordClusters?.find(c => c.clusterName === expansion.clusterTheme);
                if (targetCluster) {
                    // Add unique new keywords
                    expansion.newKeywords.forEach(newKw => {
                        if (!targetCluster.keywords.includes(newKw.term)) {
                            targetCluster.keywords.push(newKw.term);
                            targetCluster.matchTypes.push(newKw.matchType as any);
                        }
                    });
                }
            });
        }

        // 3. Merge Recommendations
        if (patch.landingPageInsights && original.landingPageAnalysis) {
            original.landingPageAnalysis.recommendations = [
                ...patch.landingPageInsights,
                ...(original.landingPageAnalysis.recommendations || [])
            ].slice(0, 7); // Keep top 7
        }

        return original;
    }

    private getVerticalGuidance(vertical: string): string {
        const guidanceMap: Record<string, string> = {
            'Local Service': 'Focus on trust, speed, and local availability. Use "Near Me", "Same Day", and "Licensed/Insured".',
            'E-commerce': 'Focus on product benefits, free shipping, and limited-time offers. Create urgency.',
            'SaaS': 'Focus on efficiency, ROI, and ease of use. Use "Free Trial", "Demo", and feature-specific benefits.',
            'Healthcare': 'Focus on compassion, expertise, and patient comfort. Build trust immediately.',
            'Restaurant': 'Focus on taste, ambiance, and urgency (reservations). Use sensory words.',
            'Other': 'Focus on unique value proposition, clear benefits, and strong call to action.'
        };
        return guidanceMap[vertical] || 'Focus on unique value proposition and clear call to action.';
    }

    /**
     * Enforce strict character limits by truncating if necessary.
     * Google Ads Limits: Headlines = 30, Descriptions = 90.
     */
    private enforceLimits(json: any): any {
        if (!json || typeof json !== 'object') return json;

        if (json.adGroupEnhancements && Array.isArray(json.adGroupEnhancements)) {
            json.adGroupEnhancements.forEach((enhancement: any) => {
                if (enhancement.newHeadlines && Array.isArray(enhancement.newHeadlines)) {
                    enhancement.newHeadlines = enhancement.newHeadlines.map((h: string) =>
                        h.length > 30 ? h.substring(0, 30) : h
                    );
                }
                if (enhancement.newDescriptions && Array.isArray(enhancement.newDescriptions)) {
                    enhancement.newDescriptions = enhancement.newDescriptions.map((d: string) =>
                        d.length > 90 ? d.substring(0, 90) : d
                    );
                }
            });
        }
        return json;
    }
}

export const blueprintAiEnhancer = new BlueprintAiEnhancer();
