import { Alert, Box, Fade, Grid, Typography } from '@mui/material';
import { WarningAmber as WarningIcon } from '@mui/icons-material';

import CustomSelect from '@/components/shared/form/custom-select';
import CustomTextBox from '@/components/shared/form/custom-text-box';

import {
  calculatePromoWindow,
  getDailyBudget,
  getMinViableBudgetWarning,
  getPacingCurve,
  type BudgetBandConfig
} from '../planning';

type Props = {
  values: any;
  setFieldValue: any;
  t: any;
  tc: any;
  budgetConfig: BudgetBandConfig;
};

const BudgetStep = ({ values, setFieldValue, t, tc, budgetConfig }: Props) => {
  const { campaignDays, dailyBudget } = getDailyBudget(values);
  const minViableWarning = getMinViableBudgetWarning(values, budgetConfig);
  const pacingCurve = getPacingCurve(values);
  const pacingSummary = `Pacing: ${pacingCurve.map((point) => `${point.label} ${point.weight}%`).join(' | ')}`;
  const recommendationLabel = minViableWarning ? `Recommended minimum: ${tc('common.currencySymbol') || '$'}${minViableWarning.threshold}/month` : '';
  const aiTradeoffHint = 'Detailed tradeoffs are generated by AI in the Review step.';

  return (
    <Fade in timeout={500}>
      <Grid container spacing={5}>
        <Grid size={{ xs: 12 }}>
          <CustomTextBox
            name="budgetMonthly"
            label={t('fields.budgetMonthly')}
            tooltip={t('fields.budgetMonthlyTooltip')}
            type="number"
            placeholder="500"
            fullWidth
            InputProps={{
              startAdornment: <Typography sx={{ mr: 1 }}>{tc('common.currencySymbol') || '$'}</Typography>
            }}
          />
          <Box sx={{ mt: 2, display: 'flex', alignItems: 'center', gap: 1 }}>
            <Typography variant="body2" color="text.secondary">
              {t('budget.dailyBudget')}:
            </Typography>
            <Typography variant="body2" sx={{ fontWeight: 600, color: 'success.main' }}>
              {tc('common.currencySymbol') || '$'}{dailyBudget}{t('budget.dailyUnit')}
            </Typography>
            {values.campaignStart && values.campaignEnd && (
              <Typography variant="caption" color="text.secondary" sx={{ ml: 1 }}>
                ({campaignDays} {t('budget.days')})
              </Typography>
            )}
          </Box>
          {values.mode === 'PRO' && (
            <Box sx={{ mt: 2 }}>
              <Typography variant="caption" color="text.secondary">
                {pacingSummary}
              </Typography>
            </Box>
          )}

          {minViableWarning && (
            <Alert severity={minViableWarning.severity} icon={<WarningIcon />} sx={{ mt: 2 }}>
              {minViableWarning.message}
              {recommendationLabel ? (
                <Typography variant="caption" sx={{ display: 'block', mt: 0.5 }}>
                  {recommendationLabel}
                </Typography>
              ) : null}
              <Typography variant="caption" sx={{ display: 'block', mt: 0.5 }}>
                {aiTradeoffHint}
              </Typography>
            </Alert>
          )}
        </Grid>
        {values.mode === 'PRO' && (
          <>
            <Grid size={{ xs: 12, md: 6 }}>
              <CustomSelect
                name="seasonality"
                label={t('fields.seasonality')}
                tooltip={t('fields.seasonalityTooltip')}
                options={[
                  { label: t('budget.seasonalityNone'), value: 'none', description: t('budget.seasonalityNoneDesc') },
                  { label: t('budget.seasonalityHoliday'), value: 'holiday', description: t('budget.seasonalityHolidayDesc') },
                  { label: t('budget.seasonalitySummer'), value: 'summer', description: t('budget.seasonalitySummerDesc') },
                  { label: t('budget.seasonalityBlackFriday'), value: 'black_friday', description: t('budget.seasonalityBlackFridayDesc') }
                ]}
                fullWidth
              />
            </Grid>
            <Grid size={{ xs: 12, md: 6 }}>
              <CustomSelect
                name="pacing"
                label={t('budget.allocation')}
                tooltip={t('fields.pacingTooltip')}
                options={[
                  { label: t('budget.pacingEven'), value: 'even', description: t('budget.pacingEvenDesc') },
                  { label: t('budget.pacingFrontLoad'), value: 'front_load', description: t('budget.pacingFrontLoadDesc') },
                  { label: t('budget.pacingRampUp'), value: 'ramp_up', description: t('budget.pacingRampUpDesc') }
                ]}
                fullWidth
              />
            </Grid>

            {values.seasonality !== 'none' && (
              <>
                <Grid size={{ xs: 12, sm: 6 }}>
                  <CustomTextBox
                    name="seasonalityStart"
                    label={t('fields.seasonalityStart')}
                    tooltip={t('fields.seasonalityStartTooltip')}
                    type="date"
                    fullWidth
                    InputLabelProps={{ shrink: true }}
                    onValueChange={(val: string | number) => {
                      const window = calculatePromoWindow(String(val), values.seasonalityEnd);

                      setFieldValue('promoWindow', window);
                    }}
                  />
                </Grid>
                <Grid size={{ xs: 12, sm: 6 }}>
                  <CustomTextBox
                    name="seasonalityEnd"
                    label={t('fields.seasonalityEnd')}
                    tooltip={t('fields.seasonalityEndTooltip')}
                    type="date"
                    fullWidth
                    InputLabelProps={{ shrink: true }}
                    onValueChange={(val: string | number) => {
                      const window = calculatePromoWindow(values.seasonalityStart, String(val));

                      setFieldValue('promoWindow', window);
                    }}
                  />
                </Grid>
                <Grid size={{ xs: 12 }}>
                  <CustomTextBox
                    name="promoWindow"
                    label={t('fields.promoWindow')}
                    tooltip={t('fields.promoWindowTooltip')}
                    type="number"
                    fullWidth
                    disabled
                    helperText={'Auto-calculated from peak start and end dates'}
                  />
                </Grid>
              </>
            )}
          </>
        )}
      </Grid>
    </Fade>
  );
};

export default BudgetStep;
